{{- if .Values.vault_settings.azure_key_vault }}
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: {{ .Values.csi.csi_default_name }}
spec:
  provider: azure
  secretObjects:
  - data:
    - key: app-secret-key
      objectName: app-secret-key
    - key: keycloak-certs-endpoint
      objectName: keycloak-certs-endpoint
    - key: message-broker-driver
      objectName: message-broker-driver
    - key: message-broker-connection-string
      objectName: message-broker-connection-string
    - key: parsing-db-password
      objectName: parsing-db-password
    - key: parsing-db
      objectName: parsing-db
    - key: parsing-db-user
      objectName: parsing-db-user
    - key: db-host
      objectName: db-host
    - key: aws-access-key-id
      objectName: aws-access-key-id
    - key: aws-secret-access-key
      objectName: aws-secret-access-key
    - key: aws-region-name
      objectName: aws-region-name
    - key: azure-form-recognizer-api
      objectName: azure-form-recognizer-api
    - key: azure-form-recognizer-key
      objectName: azure-form-recognizer-key
    - key: gcp-docai-account-info
      objectName: gcp-docai-account-info
    - key: gcp-docai-idp-client-secret
      objectName: gcp-docai-idp-client-secret
    secretName: {{ .Values.secrets.deps_parsing.secretName }}
    type: Opaque
  parameters:
    keyvaultName: {{ .Values.azure_kv_settings.keyvaultName }}
    tenantId: {{ .Values.azure_kv_settings.tenantId }}
    vaultKubernetesMountPath: {{ .Values.csi.vaultKubernetesMountPath }}
    usePodIdentity: "false"
    useVMManagedIdentity: "true"
    userAssignedIdentityID: {{ .Values.azure_kv_settings.userAssignedIdentityID }}
    resourceGroup:  {{ .Values.azure_kv_settings.resourceGroup }}
    subscriptionId: {{ .Values.azure_kv_settings.subscriptionId }}
    objects: |
      array:
        - |
          objectName: "azure-form-recognizer-api"
          objectType: secret

        - |
          objectName: "azure-form-recognizer-key"
          objectType: secret

        - |
          objectName: "parsing-db-password"
          objectType: secret

        - |
          objectName: "parsing-db"
          objectType: secret

        - |
          objectName: "parsing-db-user"
          objectType: secret

        - |
          objectName: "db-host"
          objectType: secret

        - |
          objectName: "app-secret-key"
          objectType: secret

        - |
          objectName: "keycloak-certs-endpoint"
          objectType: secret

        - |
          objectName: "message-broker-driver"
          objectType: secret

        - |
          objectName: "message-broker-connection-string"
          objectType: secret

        - |
          objectName: "aws-access-key-id"
          objectType: secret

        - |
          objectName: "aws-secret-access-key"
          objectType: secret

        - |
          objectName: "aws-region-name"
          objectType: secret

        - |
          objectName: "gcp-docai-account-info"
          objectType: secret

        - |
          objectName: "gcp-docai-idp-client-secret"
          objectType: secret
{{- end }}
