{{- if .Values.vault_settings.aws_secret_manager }}
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: {{ .Values.csi.csi_default_name }}
spec:
  provider: aws
  parameters:
    region: {{ .Values.vault_settings.aws_secret_manager_region }}
    objects: |
      - objectName: "app-secret-key"
        objectType: "secretsmanager"
        objectVersionLabel: "AWSCURRENT"
      - objectName: "keycloak-certs-endpoint"
        objectType: "secretsmanager"
        objectVersionLabel: "AWSCURRENT"
      - objectName: "message-broker-driver"
        objectType: "secretsmanager"
        objectVersionLabel: "AWSCURRENT"
      - objectName: "message-broker-connection-string"
        objectType: "secretsmanager"
        objectVersionLabel: "AWSCURRENT"
      - objectName: "parsing-db-user"
        objectType: "secretsmanager"
        objectVersionLabel: "AWSCURRENT"
      - objectName: "parsing-db-password"
        objectType: "secretsmanager"
        objectVersionLabel: "AWSCURRENT"
      - objectName: "db-host"
        objectType: "secretsmanager"
        objectVersionLabel: "AWSCURRENT"
      - objectName: "parsing-db"
        objectType: "secretsmanager"
        objectVersionLabel: "AWSCURRENT"
      - objectName: "aws-access-key-id"
        objectType: "secretsmanager"
        objectVersionLabel: "AWSCURRENT"
      - objectName: "aws-secret-access-key"
        objectType: "secretsmanager"
        objectVersionLabel: "AWSCURRENT"
      - objectName: "aws-region-name"
        objectType: "secretsmanager"
        objectVersionLabel: "AWSCURRENT"
      - objectName: "azure-form-recognizer-api"
        objectType: "secretsmanager"
        objectVersionLabel: "AWSCURRENT"
      - objectName: "azure-form-recognizer-key"
        objectType: "secretsmanager"
        objectVersionLabel: "AWSCURRENT"
      - objectName: "gcp-docai-account-info"
        objectType: "secretsmanager"
        objectVersionLabel: "AWSCURRENT"
      - objectName: "gcp-docai-idp-client-secret"
        objectType: "secretsmanager"
        objectVersionLabel: "AWSCURRENT"
  secretObjects:
    - secretName: {{ .Values.secrets.deps_parsing.secretName }}
      type: Opaque
      data:
        - objectName: "azure-form-recognizer-api"
          key: azure-form-recognizer-api
        - objectName: "azure-form-recognizer-key"
          key: azure-form-recognizer-key
        - objectName: "parsing-db-user"
          key: parsing-db-user
        - objectName: "parsing-db-password"
          key: parsing-db-password
        - objectName: "db-host"
          key: db-host
        - objectName: "parsing-db"
          key: parsing-db
        - objectName: "keycloak-certs-endpoint"
          key: keycloak-certs-endpoint
        - objectName: "message-broker-driver"
          key: message-broker-driver
        - objectName: "message-broker-connection-string"
          key: message-broker-connection-string
        - objectName: "app-secret-key"
          key: app-secret-key
        - objectName: "aws-access-key-id"
          key: aws-access-key-id
        - objectName: "aws-secret-access-key"
          key: aws-secret-access-key
        - objectName: "aws-region-name"
          key: aws-region-name
        - objectName: "gcp-docai-account-info"
          key: gcp-docai-account-info
        - objectName: "gcp-docai-idp-client-secret"
          key: gcp-docai-idp-client-secret
{{- end }}
