{{- if .Values.vault_settings.gcp_secret_manager }}
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: {{ .Values.csi.csi_default_name }}
spec:
  provider: gcp
  parameters:
    secrets: |
      - resourceName: "projects/{{ .Values.secret_project_id.id }}/secrets/keycloak-certs-endpoint/versions/latest" 
        fileName: "keycloak-certs-endpoint"
      - resourceName: "projects/{{ .Values.secret_project_id.id }}/secrets/message-broker-driver/versions/latest" 
        fileName: "message-broker-driver"
      - resourceName: "projects/{{ .Values.secret_project_id.id }}/secrets/{{ .Values.env }}-message-broker-connection-string/versions/latest" 
        fileName: "message-broker-connection-string"
      - resourceName: "projects/{{ .Values.secret_project_id.id }}/secrets/{{ .Values.env }}-database-host/versions/latest" 
        fileName: "db-host"
      - resourceName: "projects/{{ .Values.secret_project_id.id }}/secrets/{{ .Values.env }}-parsing-db-user/versions/latest" 
        fileName: "parsing-db-user"
      - resourceName: "projects/{{ .Values.secret_project_id.id }}/secrets/{{ .Values.env }}-parsing-db-password/versions/latest" 
        fileName: "parsing-db-password"
      - resourceName: "projects/{{ .Values.secret_project_id.id }}/secrets/{{ .Values.env }}-parsing-db/versions/latest" 
        fileName: "parsing-db"
      - resourceName: "projects/{{ .Values.secret_project_id.id }}/secrets/{{ .Values.env }}-azure-form-recognizer-api/versions/latest" 
        fileName: "azure-form-recognizer-api"
      - resourceName: "projects/{{ .Values.secret_project_id.id }}/secrets/{{ .Values.env }}-azure-form-recognizer-key/versions/latest" 
        fileName: "azure-form-recognizer-key"
      - resourceName: "projects/{{ .Values.secret_project_id.id }}/secrets/{{ .Values.env }}-aws-access-key-id/versions/latest" 
        fileName: "aws-access-key-id"
      - resourceName: "projects/{{ .Values.secret_project_id.id }}/secrets/{{ .Values.env }}-aws-secret-access-key/versions/latest" 
        fileName: "aws-secret-access-key"
      - resourceName: "projects/{{ .Values.secret_project_id.id }}/secrets/{{ .Values.env }}-aws-region-name/versions/latest" 
        fileName: "aws-region-name"
      - resourceName: "projects/{{ .Values.secret_project_id.id }}/secrets/{{ .Values.env }}-app-secret-key/versions/latest" 
        fileName: "app-secret-key"
      - resourceName: "projects/{{ .Values.secret_project_id.id }}/secrets/{{ .Values.env }}-gcp-docai-account/versions/latest" 
        fileName: "gcp-docai-account-info"
      - resourceName: "projects/{{ .Values.secret_project_id.id }}/secrets/{{ .Values.env }}-gcp-docai-idp/versions/latest" 
        fileName: "gcp-docai-idp-client-secret"
  secretObjects:
    - secretName: {{ .Values.secrets.deps_parsing.secretName }}
      type: Opaque
      data:
      - objectName: "app-secret-key"
        key: app-secret-key
      - objectName: "aws-region-name"
        key: aws-region-name
      - objectName: "aws-secret-access-key"
        key: aws-secret-access-key
      - objectName: "aws-access-key-id"
        key: aws-access-key-id
      - objectName: "azure-form-recognizer-api"
        key: azure-form-recognizer-api
      - objectName: "azure-form-recognizer-key"
        key: azure-form-recognizer-key
      - objectName: "db-host"
        key: db-host
      - objectName: "parsing-db-user"
        key: parsing-db-user
      - objectName: "parsing-db-password"
        key: parsing-db-password
      - objectName: "parsing-db"
        key: parsing-db
      - objectName: "message-broker-connection-string"
        key: message-broker-connection-string
      - objectName: "message-broker-driver"
        key: message-broker-driver
      - objectName: "keycloak-certs-endpoint"
        key: keycloak-certs-endpoint
      - objectName: "gcp-docai-account-info"
        key: gcp-docai-account-info
      - objectName: "gcp-docai-idp-client-secret"
        key: gcp-docai-idp-client-secret
{{- end }}
