secrets:
  deps_parsing:
    secretName: deps-parsing
  app_secret_key:
    secretName: app-secret-key
  parsing_database:
    secretName: parsing-database
  keycloak_certs_endpoint:
    secretName: keycloak-certs-endpoint
  common_secret:
    secretName: common-secret
  rabbitmq_password:
    secretName: rabbitmq-password
  security_certs:
    secretName: security-certs
  redis_password:
    secretName: redis-password
  kafka_secrets:
    secretName: kafka-secrets
  database_ssl_secret:
    secretName: database-ssl-secret
  telemetry_secrets:
    secretName: telemetry-secrets

helm_logs_job:
  serviceAccountName: gitlab-ci
  image:
    path: "/base/kubernetes-helm"
    pullPolicy: IfNotPresent
    tag: "0.1.1"
  resources: {}

registry: ""
env: ""

parsing:
  replicaCount: 1
  image:
    path: "/deps-dev-x01/deps-parsing"
    pullPolicy: IfNotPresent
    tag: ""
  imagePullSecrets: artifactory
  service:
    type: ClusterIP
    port: 8000
  resources: {}
  nodeSelector: {}
  tolerations: []
  affinity: {}

parsing_consumer:
  replicaCount: 1
  image:
    path: '/deps-dev-x01/deps-parsing'
    pullPolicy: IfNotPresent
    tag: ''
  imagePullSecrets: artifactory
  resources: {}
  nodeSelector: {}
  tolerations: []
  affinity: {}

podSecurityContext:
  runAsNonRoot: true
  runAsUser: 1000
  runAsGroup: 1000

certs_location:
  certs_default_path: "/tmp/ssl"
  database_sslcerts_path: "/home/dbcerts"

parsing_settings:
  ENV: dev

  DATABASE_PORT: '5432'
  DATABASE_DRIVER: psycopg2
  DATABASE_DIALECT: postgresql
  DATABASE_REQUIRE_SECURE_TRANSPORT: false
  DATABASE_SSLKEY_PATH: "/home/dbcerts/tls.key"
  DATABASE_SSLCERT_PATH: "/home/dbcerts/tls.crt"
  DATABASE_SSLROOTCERT_PATH: "/home/dbcerts/root.crt"

  AUTH_VERIFY_SSL: false

  LOG_LEVEL: "INFO"
  DOCUMENTATION_ENABLED: "true"

  RABBITMQ_TLS_ENABLED: false

  KAFKA_GROUP_ID: parsing
  KAFKA_AUTO_OFFSET_RESET: earliest
  KAFKA_SECURITY_ENABLED: false

  FILE_STORAGE_URL: "http://file-storage:8004"
  UNIFIER_URL: "http://unifier:8000"
  OCR_URL: "http://ocr:8000"
  TABLES_URL: "http://tables:8000"
  DOCUMENT_URL: "http://backend:8000"
  AI_FUSION_URL: "http://ai-fusion:8000"
  FILE_URL: "http://file:8000"

  OBJECT_STORAGE_MODE: "sync"
  OBJECT_STORAGE_TYPE: "file-storage"

  # by_page by_document
  AZURE_PARSING_STRATEGY: "by_document"

  # Azure Service Bus
  ASB_SUBSCRIPTION_STRATEGY: 'no_preparation'
  ASB_TOPIC_NAME: 'deps-topic'
  message_broker_asb_without_manage_permission: false

  # Telemetry
  INSTRUMENTATION_ENABLED: false
  SERVICE_NAME: deps-parsing
  EXPORTER_TYPE: azure

  MERGED_TABLES_SIMILARITY_THRESHOLD: 1.5
  MERGED_TABLES_WEIGHTS: |
    {
      "headers-repetition": {"true": 1, "false": 0},
      "text-between-tables": {"true": 0, "false": 1},
      "columns-count": {"true": 1, "false": -1},
      "indexing-continuation": {"true": 1, "false": 0},
      "columns-alignment": {"true": 0.8, "false": -0.7}
    }
  MERGE_TABLES_ENABLED: true

  GCP_DOCAI_PARSING_STRATEGY: by_document
  GCP_DOCAI_OUTPUT_DIRECTORY_PATH: "gs://temp-directory-for-document-ai/output/"
  GCP_DOCAI_PROJECT_ID: "gcp-project-id"
  GCP_DOCAI_LOCATION: "eu"
  GCP_DOCAI_FORM_RECOGNITION_PROCESSOR_ID: "processor-id"
  GCP_DOCAI_IDP_TOKEN_URL: "https://keycloak-local/auth/realms/created_manually_realm/protocol/openid-connect/token"
  GCP_DOCAI_IDP_CLIENT_ID: "oauth-client-integration-id"

  GCP_BLOB_STORAGE_BUCKET_NAME: "gcp_bucket_name"

  AWS_TEXTRACT_PARSING_STRATEGY: by_document
  AWS_TEXTRACT_PARALLELISM_FACTOR: 5
  S3_BUCKET_NAME: bucket_name
  S3_ENDPOINT_URL: https://s3.us-east-1.amazonaws.com

  IMG_ANNOTATION_LLM: ""
  IMG_ANNOTATION_GROUPING_FACTOR: 2
  IMG_ANNOTATION_PARALLELISM_FACTOR: 3
  # If empty default prompts from source code will be used
  IMG_ANNOTATION_TITLE_PROMPT: ""
  IMG_ANNOTATION_DESCRIPTION_PROMPT: ""
  IMG_ANNOTATION_CUSTOM_INSTRUCTIONS: ""
  IMG_ANNOTATION_WIDTH_PIXELS_THRESHOLD: "150"
  IMG_ANNOTATION_HEIGHT_PIXELS_THRESHOLD: "150"
  IMG_ANNOTATION_SIZE_BYTES_THRESHOLD: "20000"

helm:
  helm_logs_job_enabled: false

csi:
  csi_default_name: deps-parsing
  vault_namespace: 'k8s-dev'
  roleName: 'k8s-dev'
  vaultKubernetesMountPath: 'kubernetes-dev'

secrets_location:
  secrets_default_path: "/mnt/secrets-store"

service_account:
  serviceAccountName: 'deps-develop'

secret_project_id:
  id: ""

azure_kv_settings:
  keyvaultName: ""
  tenantId: ""
  userAssignedIdentityID: ""
  resourceGroup: ""
  subscriptionId: ""

vault_settings:
  enabled: false
  hashicorp_vault: false
  azure_key_vault: false
  gcp_secret_manager: false
  aws_secret_manager: false
  aws_secret_manager_region: ''

parsing_vault_enabled:
  env:
  - name: AUTH_CERTS_ENDPOINT
    valueFrom:
      secretKeyRef:
        name: deps-parsing
        key: keycloak-certs-endpoint
  - name: MESSAGING_DRIVER
    valueFrom:
      secretKeyRef:
        name: deps-parsing
        key: message-broker-driver
  - name: MESSAGE_BROKER_CONNECTION_STRING
    valueFrom:
      secretKeyRef:
        name: deps-parsing
        key: message-broker-connection-string
  - name: DATABASE_HOST
    valueFrom:
      secretKeyRef:
        name: deps-parsing
        key: db-host
  - name: DATABASE_DB
    valueFrom:
      secretKeyRef:
        name: deps-parsing
        key: parsing-db
  - name: DATABASE_USER
    valueFrom:
      secretKeyRef:
        name: deps-parsing
        key: parsing-db-user
  - name: DATABASE_PASSWORD
    valueFrom:
      secretKeyRef:
        name: deps-parsing
        key: parsing-db-password
  - name: AZURE_CONNECTION_STRING
    valueFrom:
      secretKeyRef:
        name: deps-parsing
        key: azure-connection-string
  - name: AZURE_CONTAINER_NAME
    valueFrom:
      secretKeyRef:
        name: deps-parsing
        key: azure-container-name
  - name: AZURE_FORM_RECOGNIZER_API_URL
    valueFrom:
      secretKeyRef:
        name: deps-parsing
        key: azure-form-recognizer-api
  - name: AZURE_FORM_RECOGNIZER_API_KEY
    valueFrom:
      secretKeyRef:
        name: deps-parsing
        key: azure-form-recognizer-key
  - name: AWS_ACCESS_KEY_ID
    valueFrom:
      secretKeyRef:
        name: deps-parsing
        key: aws-access-key-id
  - name: AWS_SECRET_ACCESS_KEY
    valueFrom:
      secretKeyRef:
        name: deps-parsing
        key: aws-secret-access-key
  - name: AWS_TEXTRACT_ACCESS_KEY_ID
    valueFrom:
      secretKeyRef:
        name: deps-parsing
        key: aws-access-key-id
  - name: AWS_TEXTRACT_SECRET_ACCESS_KEY
    valueFrom:
      secretKeyRef:
        name: deps-parsing
        key: aws-secret-access-key
  - name: AWS_TEXTRACT_REGION_NAME
    valueFrom:
      secretKeyRef:
        name: deps-parsing
        key: aws-region-name
  - name: GCP_BLOB_STORAGE_AUTH_KEY
    valueFrom:
      secretKeyRef:
        name: deps-parsing
        key: gcp-api-key
  - name: GCP_DOCAI_ACCOUNT_INFO_JSON
    valueFrom:
      secretKeyRef:
        name: deps-parsing
        key: gcp-docai-account-info
  - name: GCP_DOCAI_IDP_CLIENT_SECRET
    valueFrom:
      secretKeyRef:
        name: deps-parsing
        key: gcp-docai-idp-client-secret

parsing_vault_disabled:
  env:
  - name: AUTH_CERTS_ENDPOINT
    valueFrom:
      secretKeyRef:
        name: keycloak-certs-endpoint
        key: keycloak-certs-endpoint
  - name: MESSAGING_DRIVER
    valueFrom:
      secretKeyRef:
        name: common-secret
        key: message-broker-driver
  - name: MESSAGE_BROKER_CONNECTION_STRING
    valueFrom:
      secretKeyRef:
        name: common-secret
        key: message-broker-connection-string
  - name: DATABASE_HOST
    valueFrom:
      secretKeyRef:
        name: common-secret
        key: database-host
  - name: DATABASE_DB
    valueFrom:
      secretKeyRef:
        name: parsing-database
        key: database-db
  - name: DATABASE_USER
    valueFrom:
      secretKeyRef:
        name: parsing-database
        key: user
  - name: DATABASE_PASSWORD
    valueFrom:
      secretKeyRef:
        name: parsing-database
        key: password
  - name: AZURE_CONNECTION_STRING
    valueFrom:
      secretKeyRef:
        name: azure-blob-storage
        key: azure-connection-string
  - name: AZURE_CONTAINER_NAME
    valueFrom:
      secretKeyRef:
        name: azure-blob-storage
        key: azure-container-name
  - name: AZURE_FORM_RECOGNIZER_API_URL
    valueFrom:
      secretKeyRef:
        name: azure-credentials
        key: azure-form-recognizer-api
  - name: AZURE_FORM_RECOGNIZER_API_KEY
    valueFrom:
      secretKeyRef:
        name: azure-credentials
        key: azure-form-recognizer-key
  - name: AWS_ACCESS_KEY_ID
    valueFrom:
      secretKeyRef:
        name: file-storage-aws-credentials
        key: aws-access-key-id
  - name: AWS_SECRET_ACCESS_KEY
    valueFrom:
      secretKeyRef:
        name: file-storage-aws-credentials
        key: aws-secret-access-key
  - name: AWS_TEXTRACT_ACCESS_KEY_ID
    valueFrom:
      secretKeyRef:
        name: ocr-aws-credentials
        key: aws-access-key-id
  - name: AWS_TEXTRACT_SECRET_ACCESS_KEY
    valueFrom:
      secretKeyRef:
        name: ocr-aws-credentials
        key: aws-secret-access-key
  - name: AWS_TEXTRACT_REGION_NAME
    valueFrom:
      secretKeyRef:
        name: ocr-aws-credentials
        key: aws-region-name
  - name: GCP_BLOB_STORAGE_AUTH_KEY
    valueFrom:
      secretKeyRef:
        name: gcp-credentials
        key: gcp-api-key
  - name: GCP_DOCAI_ACCOUNT_INFO_JSON
    valueFrom:
      secretKeyRef:
        name: gcp-credentials
        key: gcp-docai-account-info
  - name: GCP_DOCAI_IDP_CLIENT_SECRET
    valueFrom:
      secretKeyRef:
        name: gcp-credentials
        key: gcp-docai-idp-client-secret

parsing_consumer_vault_enabled:
  env:
  - name: SECRET_KEY
    valueFrom:
      secretKeyRef:
        name: deps-parsing
        key: app-secret-key
  - name: AUTH_CERTS_ENDPOINT
    valueFrom:
      secretKeyRef:
        name: deps-parsing
        key: keycloak-certs-endpoint
  - name: MESSAGING_DRIVER
    valueFrom:
      secretKeyRef:
        name: deps-parsing
        key: message-broker-driver
  - name: MESSAGE_BROKER_CONNECTION_STRING
    valueFrom:
      secretKeyRef:
        name: deps-parsing
        key: message-broker-connection-string
  - name: DATABASE_HOST
    valueFrom:
      secretKeyRef:
        name: deps-parsing
        key: db-host
  - name: DATABASE_DB
    valueFrom:
      secretKeyRef:
        name: deps-parsing
        key: parsing-db
  - name: DATABASE_USER
    valueFrom:
      secretKeyRef:
        name: deps-parsing
        key: parsing-db-user
  - name: DATABASE_PASSWORD
    valueFrom:
      secretKeyRef:
        name: deps-parsing
        key: parsing-db-password
  - name: AZURE_CONNECTION_STRING
    valueFrom:
      secretKeyRef:
        name: deps-parsing
        key: azure-connection-string
  - name: AZURE_CONTAINER_NAME
    valueFrom:
      secretKeyRef:
        name: deps-parsing
        key: azure-container-name
  - name: AZURE_FORM_RECOGNIZER_API_URL
    valueFrom:
      secretKeyRef:
        name: deps-parsing
        key: azure-form-recognizer-api
  - name: AZURE_FORM_RECOGNIZER_API_KEY
    valueFrom:
      secretKeyRef:
        name: deps-parsing
        key: azure-form-recognizer-key
  - name: AWS_ACCESS_KEY_ID
    valueFrom:
      secretKeyRef:
        name: deps-parsing
        key: aws-access-key-id
  - name: AWS_SECRET_ACCESS_KEY
    valueFrom:
      secretKeyRef:
        name: deps-parsing
        key: aws-secret-access-key
  - name: S3_ENDPOINT_URL
    valueFrom:
      secretKeyRef:
        name: deps-parsing
        key: aws-storage-s3-endpoint-url
  - name: S3_BUCKET_NAME
    valueFrom:
      secretKeyRef:
        name: deps-parsing
        key: aws-storage-s3-bucket-name
  - name: AWS_TEXTRACT_ACCESS_KEY_ID
    valueFrom:
      secretKeyRef:
        name: deps-parsing
        key: aws-access-key-id
  - name: AWS_TEXTRACT_SECRET_ACCESS_KEY
    valueFrom:
      secretKeyRef:
        name: deps-parsing
        key: aws-secret-access-key
  - name: AWS_TEXTRACT_REGION_NAME
    valueFrom:
      secretKeyRef:
        name: deps-parsing
        key: aws-region-name
  - name: GCP_BLOB_STORAGE_AUTH_KEY
    valueFrom:
      secretKeyRef:
        name: deps-parsing
        key: gcp-api-key
  - name: GCP_DOCAI_ACCOUNT_INFO_JSON
    valueFrom:
      secretKeyRef:
        name: deps-parsing
        key: gcp-docai-account-info
  - name: GCP_DOCAI_IDP_CLIENT_SECRET
    valueFrom:
      secretKeyRef:
        name: deps-parsing
        key: gcp-docai-idp-client-secret

parsing_consumer_vault_disabled:
  env:
  - name: SECRET_KEY
    valueFrom:
      secretKeyRef:
        name: app-secret-key
        key: app-secret-key
  - name: AUTH_CERTS_ENDPOINT
    valueFrom:
      secretKeyRef:
        name: keycloak-certs-endpoint
        key: keycloak-certs-endpoint
  - name: MESSAGING_DRIVER
    valueFrom:
      secretKeyRef:
        name: common-secret
        key: message-broker-driver
  - name: MESSAGE_BROKER_CONNECTION_STRING
    valueFrom:
      secretKeyRef:
        name: common-secret
        key: message-broker-connection-string
  - name: DATABASE_HOST
    valueFrom:
      secretKeyRef:
        name: common-secret
        key: database-host
  - name: DATABASE_DB
    valueFrom:
      secretKeyRef:
        name: parsing-database
        key: database-db
  - name: DATABASE_USER
    valueFrom:
      secretKeyRef:
        name: parsing-database
        key: user
  - name: DATABASE_PASSWORD
    valueFrom:
      secretKeyRef:
        name: parsing-database
        key: password
  - name: AZURE_CONNECTION_STRING
    valueFrom:
      secretKeyRef:
        name: azure-blob-storage
        key: azure-connection-string
  - name: AZURE_CONTAINER_NAME
    valueFrom:
      secretKeyRef:
        name: azure-blob-storage
        key: azure-container-name
  - name: AZURE_FORM_RECOGNIZER_API_URL
    valueFrom:
      secretKeyRef:
        name: azure-credentials
        key: azure-form-recognizer-api
  - name: AZURE_FORM_RECOGNIZER_API_KEY
    valueFrom:
      secretKeyRef:
        name: azure-credentials
        key: azure-form-recognizer-key
  - name: AWS_ACCESS_KEY_ID
    valueFrom:
      secretKeyRef:
        name: file-storage-aws-credentials
        key: aws-access-key-id
  - name: AWS_SECRET_ACCESS_KEY
    valueFrom:
      secretKeyRef:
        name: file-storage-aws-credentials
        key: aws-secret-access-key
  - name: AWS_TEXTRACT_ACCESS_KEY_ID
    valueFrom:
      secretKeyRef:
        name: ocr-aws-credentials
        key: aws-access-key-id
  - name: AWS_TEXTRACT_SECRET_ACCESS_KEY
    valueFrom:
      secretKeyRef:
        name: ocr-aws-credentials
        key: aws-secret-access-key
  - name: AWS_TEXTRACT_REGION_NAME
    valueFrom:
      secretKeyRef:
        name: ocr-aws-credentials
        key: aws-region-name
  - name: GCP_BLOB_STORAGE_AUTH_KEY
    valueFrom:
      secretKeyRef:
        name: gcp-credentials
        key: gcp-api-key
  - name: GCP_DOCAI_ACCOUNT_INFO_JSON
    valueFrom:
      secretKeyRef:
        name: gcp-credentials
        key: gcp-docai-account-info
  - name: GCP_DOCAI_IDP_CLIENT_SECRET
    valueFrom:
      secretKeyRef:
        name: gcp-credentials
        key: gcp-docai-idp-client-secret
