apiVersion: v1
kind: Service
metadata:
  name: parsing
  labels:
    {{- include "deps-parsing.labels" . | nindent 4 }}
spec:
  type: {{ .Values.parsing.service.type }}
  ports:
    - port: {{ .Values.parsing.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "deps-parsing.selectorLabels" . | nindent 4 }}
