parsing:
  image:
    path: "/deps-platform/deps-parsing"
  resources: {}

parsing_settings:
  ENV: staging
  LOG_LEVEL: "INFO"

  DATABASE_REQUIRE_SECURE_TRANSPORT: false

  OBJECT_STORAGE_TYPE: aws
  S3_BUCKET_NAME: bucket_name
  S3_ENDPOINT_URL: https://s3.eu-central-1.amazonaws.com

migration_settings:
  DATABASE_REQUIRE_SECURE_TRANSPORT: false

parsing_consumer:
  image:
    path: "/deps-platform/deps-parsing"

migrator:
  image:
    path: "/deps-platform/deps-parsing-migrator"

helm:
  helm_logs_job_enabled: false

csi:
  vault_namespace: 'k8s-staging'
  roleName: 'k8s-staging'
  vaultKubernetesMountPath: 'kubernetes-staging'

service_account:
  serviceAccountName: 'deps-staging'
