parsing:
  image:
    path: "/deps-platform/deps-parsing"
  resources: {}

parsing_settings:
  ENV: ins
  LOG_LEVEL: "INFO"

  DATABASE_REQUIRE_SECURE_TRANSPORT: false

  MERGE_TABLES_ENABLED: false

  OBJECT_STORAGE_TYPE: aws
  S3_BUCKET_NAME: bucket_name
  S3_ENDPOINT_URL: https://s3.us-east-1.amazonaws.com

migration_settings:
  DATABASE_REQUIRE_SECURE_TRANSPORT: false

parsing_consumer:
  image:
    path: "/deps-platform/deps-parsing"

migrator:
  image:
    path: "/deps-platform/deps-parsing-migrator"

helm:
  helm_logs_job_enabled: false

csi:
  vault_namespace: 'k8s-ins'
  roleName: 'k8s-ins'
  vaultKubernetesMountPath: 'kubernetes-ins'

service_account:
  serviceAccountName: 'deps-insurance'
